In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [17]:
df_train = pd.read_csv('/kaggle/NLP_DisasterTweets/train.csv')
df_test = pd.read_csv('/kaggle/NLP_DisasterTweets/test.csv')
df_sub = pd.read_csv('/kaggle/NLP_DisasterTweets/sample_submission.csv')

In [18]:
df_train

,id,keyword,location,text,target
0,1,NaN,NaN,Our Deeds are the Reason of this #earthquake M...,1
1,4,NaN,NaN,Forest fire near La Ronge Sask. Canada,1
2,5,NaN,NaN,All residents asked to 'shelter in place' are ...,1
3,6,NaN,NaN,"13,000 people receive #wildfires evacuation or...",1
4,7,NaN,NaN,Just got sent this photo from Ruby #Alaska as ...,1
...,...,...,...,...,...
7608,10869,NaN,NaN,Two giant cranes holding a bridge collapse int...,1
7609,10870,NaN,NaN,@aria_ahrary @TheTawniest The out of control w...,1
7610,10871,NaN,NaN,M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...,1
7611,10872,NaN,NaN,Police investigating after an e-bike collided ...,1
7612,10873,NaN,NaN,The Latest: More Homes Razed by Northern Calif...,1

In [19]:
df_test

,id,keyword,location,text
0,0,NaN,NaN,Just happened a terrible car crash
1,2,NaN,NaN,"Heard about #earthquake is different cities, s..."
2,3,NaN,NaN,"there is a forest fire at spot pond, geese are..."
3,9,NaN,NaN,Apocalypse lighting. #Spokane #wildfires
4,11,NaN,NaN,Typhoon Soudelor kills 28 in China and Taiwan
...,...,...,...,...
3258,10861,NaN,NaN,EARTHQUAKE SAFETY LOS ANGELES ÛÒ SAFETY FASTE...
3259,10865,NaN,NaN,Storm in RI worse than last hurricane. My city...
3260,10868,NaN,NaN,Green Line derailment in Chicago http://t.co/U...
3261,10874,NaN,NaN,MEG issues Hazardous Weather Outlook (HWO) htt...
3262,10875,NaN,NaN,#CityofCalgary has activated its Municipal Eme...

In [20]:
X = df_train['text']
y = df_train['target']

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [22]:
from sklearn.model_selection import GridSearchCV

In [23]:
from sklearn.pipeline import Pipeline

In [27]:
from sklearn.tree import DecisionTreeClassifier

In [26]:
tfidf = TfidfVectorizer()

In [28]:
model = DecisionTreeClassifier()

In [29]:
pipe = Pipeline([('tfidf', tfidf), ('model', model)])

In [36]:
params = {
    'tfidf__max_features': [1000, 2000, 5000],
    'tfidf__ngram_range': [(1, 1), (1, 2)],
    'model__max_depth': [5, 10, 20, None],
    'model__min_samples_split': [2, 5, 10]
}

In [37]:
X_test = df_test['text']

In [39]:
final_model = GridSearchCV(pipe, params, cv=3, verbose=2)

In [41]:
final_model.fit(X, y)

Fitting 3 folds for each of 72 candidates, totalling 216 fits
[CV] END model__max_depth=5, model__min_samples_split=2, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END model__max_depth=5, model__min_samples_split=2, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.4s
[CV] END model__max_depth=5, model__min_samples_split=2, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.9s
[CV] END model__max_depth=5, model__min_samples_split=2, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.7s
[CV] END model__max_depth=5, model__min_samples_split=2, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.7s
[CV] END model__max_depth=5, model__min_samples_split=2, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.6s
[CV] END model__max_depth=5, model__min_samples_split=2, tfidf__max_features=2000, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END model__max_depth=5, model__min_samples_split=2, tfidf__max_features=2000, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END model__max_depth=5, model__min_samples_split=2, tfidf__max_features=2000, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END model__max_depth=5, model__min_samples_split=2, tfidf__max_features=2000, tfidf__ngram_range=(1, 2); total time=   0.4s
[CV] END model__max_depth=5, model__min_samples_split=2, tfidf__max_features=2000, tfidf__ngram_range=(1, 2); total time=   0.4s
[CV] END model__max_depth=5, model__min_samples_split=2, tfidf__max_features=2000, tfidf__ngram_range=(1, 2); total time=   0.4s
[CV] END model__max_depth=5, model__min_samples_split=2, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END model__max_depth=5, model__min_samples_split=2, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END model__max_depth=5, model__min_samples_split=2, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END model__max_depth=5, model__min_samples_split=2, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END model__max_depth=5, model__min_samples_split=2, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END model__max_depth=5, model__min_samples_split=2, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   0.6s
[CV] END model__max_depth=5, model__min_samples_split=5, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END model__max_depth=5, model__min_samples_split=5, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END model__max_depth=5, model__min_samples_split=5, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END model__max_depth=5, model__min_samples_split=5, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END model__max_depth=5, model__min_samples_split=5, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.6s
[CV] END model__max_depth=5, model__min_samples_split=5, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END model__max_depth=5, model__min_samples_split=5, tfidf__max_features=2000, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END model__max_depth=5, model__min_samples_split=5, tfidf__max_features=2000, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END model__max_depth=5, model__min_samples_split=5, tfidf__max_features=2000, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END model__max_depth=5, model__min_samples_split=5, tfidf__max_features=2000, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END model__max_depth=5, model__min_samples_split=5, tfidf__max_features=2000, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END model__max_depth=5, model__min_samples_split=5, tfidf__max_features=2000, tfidf__ngram_range=(1, 2); total time=   0.6s
[CV] END model__max_depth=5, model__min_samples_split=5, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END model__max_depth=5, model__min_samples_split=5, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END model__max_depth=5, model__min_samples_split=5, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END model__max_depth=5, model__min_samples_split=5, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END model__max_depth=5, model__min_samples_split=5, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   0.7s
[CV] END model__max_depth=5, model__min_samples_split=5, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   0.8s
[CV] END model__max_depth=5, model__min_samples_split=10, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.3s
[CV] END model__max_depth=5, model__min_samples_split=10, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.3s
[CV] END model__max_depth=5, model__min_samples_split=10, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.3s
[CV] END model__max_depth=5, model__min_samples_split=10, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END model__max_depth=5, model__min_samples_split=10, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END model__max_depth=5, model__min_samples_split=10, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END model__max_depth=5, model__min_samples_split=10, tfidf__max_features=2000, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END model__max_depth=5, model__min_samples_split=10, tfidf__max_features=2000, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END model__max_depth=5, model__min_samples_split=10, tfidf__max_features=2000, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END model__max_depth=5, model__min_samples_split=10, tfidf__max_features=2000, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END model__max_depth=5, model__min_samples_split=10, tfidf__max_features=2000, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END model__max_depth=5, model__min_samples_split=10, tfidf__max_features=2000, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END model__max_depth=5, model__min_samples_split=10, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END model__max_depth=5, model__min_samples_split=10, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END model__max_depth=5, model__min_samples_split=10, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END model__max_depth=5, model__min_samples_split=10, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END model__max_depth=5, model__min_samples_split=10, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END model__max_depth=5, model__min_samples_split=10, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END model__max_depth=10, model__min_samples_split=2, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END model__max_depth=10, model__min_samples_split=2, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END model__max_depth=10, model__min_samples_split=2, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.3s
[CV] END model__max_depth=10, model__min_samples_split=2, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END model__max_depth=10, model__min_samples_split=2, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END model__max_depth=10, model__min_samples_split=2, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END model__max_depth=10, model__min_samples_split=2, tfidf__max_features=2000, tfidf__ngram_range=(1, 1); total time=   0.3s
[CV] END model__max_depth=10, model__min_samples_split=2, tfidf__max_features=2000, tfidf__ngram_range=(1, 1); total time=   0.3s
[CV] END model__max_depth=10, model__min_samples_split=2, tfidf__max_features=2000, tfidf__ngram_range=(1, 1); total time=   0.3s
[CV] END model__max_depth=10, model__min_samples_split=2, tfidf__max_features=2000, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END model__max_depth=10, model__min_samples_split=2, tfidf__max_features=2000, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END model__max_depth=10, model__min_samples_split=2, tfidf__max_features=2000, tfidf__ngram_range=(1, 2); total time=   0.6s
[CV] END model__max_depth=10, model__min_samples_split=2, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   0.5s
[CV] END model__max_depth=10, model__min_samples_split=2, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   0.5s
[CV] END model__max_depth=10, model__min_samples_split=2, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   0.5s
[CV] END model__max_depth=10, model__min_samples_split=2, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   0.9s
[CV] END model__max_depth=10, model__min_samples_split=2, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   0.6s
[CV] END model__max_depth=10, model__min_samples_split=2, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   0.6s
[CV] END model__max_depth=10, model__min_samples_split=5, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END model__max_depth=10, model__min_samples_split=5, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END model__max_depth=10, model__min_samples_split=5, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END model__max_depth=10, model__min_samples_split=5, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END model__max_depth=10, model__min_samples_split=5, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END model__max_depth=10, model__min_samples_split=5, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END model__max_depth=10, model__min_samples_split=5, tfidf__max_features=2000, tfidf__ngram_range=(1, 1); total time=   0.3s
[CV] END model__max_depth=10, model__min_samples_split=5, tfidf__max_features=2000, tfidf__ngram_range=(1, 1); total time=   0.3s
[CV] END model__max_depth=10, model__min_samples_split=5, tfidf__max_features=2000, tfidf__ngram_range=(1, 1); total time=   0.3s
[CV] END model__max_depth=10, model__min_samples_split=5, tfidf__max_features=2000, tfidf__ngram_range=(1, 2); total time=   0.6s
[CV] END model__max_depth=10, model__min_samples_split=5, tfidf__max_features=2000, tfidf__ngram_range=(1, 2); total time=   0.6s
[CV] END model__max_depth=10, model__min_samples_split=5, tfidf__max_features=2000, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END model__max_depth=10, model__min_samples_split=5, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   0.3s
[CV] END model__max_depth=10, model__min_samples_split=5, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   0.3s
[CV] END model__max_depth=10, model__min_samples_split=5, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   0.3s
[CV] END model__max_depth=10, model__min_samples_split=5, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   0.6s
[CV] END model__max_depth=10, model__min_samples_split=5, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   0.6s
[CV] END model__max_depth=10, model__min_samples_split=5, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   0.6s
[CV] END model__max_depth=10, model__min_samples_split=10, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END model__max_depth=10, model__min_samples_split=10, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END model__max_depth=10, model__min_samples_split=10, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END model__max_depth=10, model__min_samples_split=10, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END model__max_depth=10, model__min_samples_split=10, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END model__max_depth=10, model__min_samples_split=10, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.8s
[CV] END model__max_depth=10, model__min_samples_split=10, tfidf__max_features=2000, tfidf__ngram_range=(1, 1); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_split=10, tfidf__max_features=2000, tfidf__ngram_range=(1, 1); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_split=10, tfidf__max_features=2000, tfidf__ngram_range=(1, 1); total time=   0.4s
[CV] END model__max_depth=10, model__min_samples_split=10, tfidf__max_features=2000, tfidf__ngram_range=(1, 2); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_split=10, tfidf__max_features=2000, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END model__max_depth=10, model__min_samples_split=10, tfidf__max_features=2000, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END model__max_depth=10, model__min_samples_split=10, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   0.3s
[CV] END model__max_depth=10, model__min_samples_split=10, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   0.3s
[CV] END model__max_depth=10, model__min_samples_split=10, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   0.3s
[CV] END model__max_depth=10, model__min_samples_split=10, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END model__max_depth=10, model__min_samples_split=10, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   0.6s
[CV] END model__max_depth=10, model__min_samples_split=10, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   0.6s
[CV] END model__max_depth=20, model__min_samples_split=2, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.3s
[CV] END model__max_depth=20, model__min_samples_split=2, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.3s
[CV] END model__max_depth=20, model__min_samples_split=2, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.3s
[CV] END model__max_depth=20, model__min_samples_split=2, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.6s
[CV] END model__max_depth=20, model__min_samples_split=2, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END model__max_depth=20, model__min_samples_split=2, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.6s
[CV] END model__max_depth=20, model__min_samples_split=2, tfidf__max_features=2000, tfidf__ngram_range=(1, 1); total time=   0.4s
[CV] END model__max_depth=20, model__min_samples_split=2, tfidf__max_features=2000, tfidf__ngram_range=(1, 1); total time=   0.4s
[CV] END model__max_depth=20, model__min_samples_split=2, tfidf__max_features=2000, tfidf__ngram_range=(1, 1); total time=   0.4s
[CV] END model__max_depth=20, model__min_samples_split=2, tfidf__max_features=2000, tfidf__ngram_range=(1, 2); total time=   0.6s
[CV] END model__max_depth=20, model__min_samples_split=2, tfidf__max_features=2000, tfidf__ngram_range=(1, 2); total time=   0.6s
[CV] END model__max_depth=20, model__min_samples_split=2, tfidf__max_features=2000, tfidf__ngram_range=(1, 2); total time=   1.0s
[CV] END model__max_depth=20, model__min_samples_split=2, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   1.0s
[CV] END model__max_depth=20, model__min_samples_split=2, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   0.7s
[CV] END model__max_depth=20, model__min_samples_split=2, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   0.7s
[CV] END model__max_depth=20, model__min_samples_split=2, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   0.9s
[CV] END model__max_depth=20, model__min_samples_split=2, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   0.7s
[CV] END model__max_depth=20, model__min_samples_split=2, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   0.8s
[CV] END model__max_depth=20, model__min_samples_split=5, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.3s
[CV] END model__max_depth=20, model__min_samples_split=5, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.3s
[CV] END model__max_depth=20, model__min_samples_split=5, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.4s
[CV] END model__max_depth=20, model__min_samples_split=5, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.6s
[CV] END model__max_depth=20, model__min_samples_split=5, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END model__max_depth=20, model__min_samples_split=5, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.6s
[CV] END model__max_depth=20, model__min_samples_split=5, tfidf__max_features=2000, tfidf__ngram_range=(1, 1); total time=   0.4s
[CV] END model__max_depth=20, model__min_samples_split=5, tfidf__max_features=2000, tfidf__ngram_range=(1, 1); total time=   0.4s
[CV] END model__max_depth=20, model__min_samples_split=5, tfidf__max_features=2000, tfidf__ngram_range=(1, 1); total time=   0.4s
[CV] END model__max_depth=20, model__min_samples_split=5, tfidf__max_features=2000, tfidf__ngram_range=(1, 2); total time=   1.1s
[CV] END model__max_depth=20, model__min_samples_split=5, tfidf__max_features=2000, tfidf__ngram_range=(1, 2); total time=   1.1s
[CV] END model__max_depth=20, model__min_samples_split=5, tfidf__max_features=2000, tfidf__ngram_range=(1, 2); total time=   0.6s
[CV] END model__max_depth=20, model__min_samples_split=5, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   0.4s
[CV] END model__max_depth=20, model__min_samples_split=5, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   0.5s
[CV] END model__max_depth=20, model__min_samples_split=5, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   0.6s
[CV] END model__max_depth=20, model__min_samples_split=5, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   1.1s
[CV] END model__max_depth=20, model__min_samples_split=5, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   1.2s
[CV] END model__max_depth=20, model__min_samples_split=5, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   0.8s
[CV] END model__max_depth=20, model__min_samples_split=10, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.3s
[CV] END model__max_depth=20, model__min_samples_split=10, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.3s
[CV] END model__max_depth=20, model__min_samples_split=10, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.3s
[CV] END model__max_depth=20, model__min_samples_split=10, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.6s
[CV] END model__max_depth=20, model__min_samples_split=10, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.6s
[CV] END model__max_depth=20, model__min_samples_split=10, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.6s
[CV] END model__max_depth=20, model__min_samples_split=10, tfidf__max_features=2000, tfidf__ngram_range=(1, 1); total time=   0.4s
[CV] END model__max_depth=20, model__min_samples_split=10, tfidf__max_features=2000, tfidf__ngram_range=(1, 1); total time=   0.4s
[CV] END model__max_depth=20, model__min_samples_split=10, tfidf__max_features=2000, tfidf__ngram_range=(1, 1); total time=   0.4s

GridSearchCV(cv=3,
             estimator=Pipeline(steps=[('tfidf', TfidfVectorizer()),
                                       ('model', DecisionTreeClassifier())]),
             param_grid={'model__max_depth': [5, 10, 20, None],
                         'model__min_samples_split': [2, 5, 10],
                         'tfidf__max_features': [1000, 2000, 5000],
                         'tfidf__ngram_range': [(1, 1), (1, 2)]},
             verbose=2)

In [42]:
y_pred = final_model.predict(X_test)

In [43]:
df_sub['target'] = y_pred

In [44]:
df_sub.to_csv('sub.csv', index=False, index_label=False)

**WITH RANDOM FOREST**

In [45]:
X = df_train['text']
y = df_train['target']

In [54]:
X_test = df_test['text']

In [47]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier

In [48]:
tfidf = TfidfVectorizer()

In [49]:
model = RandomForestClassifier()

In [50]:
pipe = Pipeline([('tfidf', tfidf), ('model', model)])

In [60]:
params = {
    'tfidf__max_features': [1000, 3000, 5000],
    'tfidf__ngram_range': [(1, 1), (1, 2), (1, 3)],
    'model__n_estimators': [100, 200, 300],
    'model__max_depth': [10, 20, 30, None],
    'model__min_samples_split': [2, 5, 10],
    'model__min_samples_leaf': [1, 2, 4]
}

In [61]:
final_model = GridSearchCV(pipe, params, cv=3, verbose=2)

In [62]:
final_model.fit(X, y)

Fitting 3 folds for each of 972 candidates, totalling 2916 fits
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.6s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.6s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.6s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.8s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.8s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   0.9s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=1000, tfidf__ngram_range=(1, 3); total time=   1.5s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=1000, tfidf__ngram_range=(1, 3); total time=   1.8s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=1000, tfidf__ngram_range=(1, 3); total time=   1.2s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=3000, tfidf__ngram_range=(1, 1); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=3000, tfidf__ngram_range=(1, 1); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=3000, tfidf__ngram_range=(1, 1); total time=   0.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=3000, tfidf__ngram_range=(1, 2); total time=   1.0s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=3000, tfidf__ngram_range=(1, 2); total time=   1.0s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=3000, tfidf__ngram_range=(1, 2); total time=   1.0s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=3000, tfidf__ngram_range=(1, 3); total time=   1.3s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=3000, tfidf__ngram_range=(1, 3); total time=   1.2s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=3000, tfidf__ngram_range=(1, 3); total time=   1.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   1.0s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   1.1s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   0.9s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   1.0s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   0.9s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   1.0s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=5000, tfidf__ngram_range=(1, 3); total time=   1.3s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=5000, tfidf__ngram_range=(1, 3); total time=   1.3s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100, tfidf__max_features=5000, tfidf__ngram_range=(1, 3); total time=   1.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   1.1s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   1.1s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   1.5s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   2.1s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   1.5s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   1.5s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=1000, tfidf__ngram_range=(1, 3); total time=   1.8s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=1000, tfidf__ngram_range=(1, 3); total time=   1.8s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=1000, tfidf__ngram_range=(1, 3); total time=   1.9s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=3000, tfidf__ngram_range=(1, 1); total time=   1.1s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=3000, tfidf__ngram_range=(1, 1); total time=   1.5s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=3000, tfidf__ngram_range=(1, 1); total time=   1.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=3000, tfidf__ngram_range=(1, 2); total time=   1.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=3000, tfidf__ngram_range=(1, 2); total time=   1.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=3000, tfidf__ngram_range=(1, 2); total time=   1.5s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=3000, tfidf__ngram_range=(1, 3); total time=   1.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=3000, tfidf__ngram_range=(1, 3); total time=   1.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=3000, tfidf__ngram_range=(1, 3); total time=   1.8s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   1.6s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   1.6s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   1.2s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   1.5s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   1.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   1.6s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=5000, tfidf__ngram_range=(1, 3); total time=   1.8s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=5000, tfidf__ngram_range=(1, 3); total time=   1.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200, tfidf__max_features=5000, tfidf__ngram_range=(1, 3); total time=   2.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=300, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   1.9s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=300, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   1.6s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=300, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   1.6s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=300, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   2.0s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=300, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   1.9s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=300, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   2.2s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=300, tfidf__max_features=1000, tfidf__ngram_range=(1, 3); total time=   3.1s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=300, tfidf__max_features=1000, tfidf__ngram_range=(1, 3); total time=   2.2s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=300, tfidf__max_features=1000, tfidf__ngram_range=(1, 3); total time=   2.3s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=300, tfidf__max_features=3000, tfidf__ngram_range=(1, 1); total time=   1.5s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=300, tfidf__max_features=3000, tfidf__ngram_range=(1, 1); total time=   1.4s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=300, tfidf__max_features=3000, tfidf__ngram_range=(1, 1); total time=   1.6s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=300, tfidf__max_features=3000, tfidf__ngram_range=(1, 2); total time=   2.9s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=300, tfidf__max_features=3000, tfidf__ngram_range=(1, 2); total time=   1.8s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=300, tfidf__max_features=3000, tfidf__ngram_range=(1, 2); total time=   2.0s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=300, tfidf__max_features=3000, tfidf__ngram_range=(1, 3); total time=   2.3s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=300, tfidf__max_features=3000, tfidf__ngram_range=(1, 3); total time=   2.2s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=300, tfidf__max_features=3000, tfidf__ngram_range=(1, 3); total time=   2.9s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=300, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   2.2s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=300, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   1.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=300, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   1.7s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=300, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   2.0s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=300, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   2.0s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=300, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   2.2s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=300, tfidf__max_features=5000, tfidf__ngram_range=(1, 3); total time=   3.1s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=300, tfidf__max_features=5000, tfidf__ngram_range=(1, 3); total time=   2.3s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=300, tfidf__max_features=5000, tfidf__ngram_range=(1, 3); total time=   2.5s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.6s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.6s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   0.6s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   1.0s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   1.0s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=1000, tfidf__ngram_range=(1, 2); total time=   1.2s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=1000, tfidf__ngram_range=(1, 3); total time=   2.0s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=1000, tfidf__ngram_range=(1, 3); total time=   1.3s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=1000, tfidf__ngram_range=(1, 3); total time=   1.3s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=3000, tfidf__ngram_range=(1, 1); total time=   0.6s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=3000, tfidf__ngram_range=(1, 1); total time=   0.6s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=3000, tfidf__ngram_range=(1, 1); total time=   0.6s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=3000, tfidf__ngram_range=(1, 2); total time=   0.9s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=3000, tfidf__ngram_range=(1, 2); total time=   0.9s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=3000, tfidf__ngram_range=(1, 2); total time=   0.9s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=3000, tfidf__ngram_range=(1, 3); total time=   1.2s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=3000, tfidf__ngram_range=(1, 3); total time=   1.2s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=3000, tfidf__ngram_range=(1, 3); total time=   1.9s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   0.9s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   0.6s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=5000, tfidf__ngram_range=(1, 1); total time=   0.6s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   0.9s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   0.9s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=5000, tfidf__ngram_range=(1, 2); total time=   0.9s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=5000, tfidf__ngram_range=(1, 3); total time=   1.1s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=5000, tfidf__ngram_range=(1, 3); total time=   1.3s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100, tfidf__max_features=5000, tfidf__ngram_range=(1, 3); total time=   1.3s
[CV] END model__max_depth=10, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=200, tfidf__max_features=1000, tfidf__ngram_range=(1, 1); total time=   1.1s

GridSearchCV(cv=3,
             estimator=Pipeline(steps=[('tfidf', TfidfVectorizer()),
                                       ('model', RandomForestClassifier())]),
             param_grid={'model__max_depth': [10, 20, 30, None],
                         'model__min_samples_leaf': [1, 2, 4],
                         'model__min_samples_split': [2, 5, 10],
                         'model__n_estimators': [100, 200, 300],
                         'tfidf__max_features': [1000, 3000, 5000],
                         'tfidf__ngram_range': [(1, 1), (1, 2), (1, 3)]},
             verbose=2)

In [63]:
y_pred = final_model.predict(X_test)

In [64]:
df_sub['target'] = y_pred

In [65]:
df_sub.to_csv('final_sub.csv', index=False, index_label=False)